// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (*Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (*Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (*Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteComment(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	FindByEmailUser(ctx context.Context, email string) (*FindByEmailUserRow, error)
	GetCategories(ctx context.Context) ([]*Category, error)
	GetCategory(ctx context.Context, id int32) (*Category, error)
	GetComment(ctx context.Context, id int32) (*Comment, error)
	GetComments(ctx context.Context) ([]*Comment, error)
	GetPost(ctx context.Context, id int32) (*GetPostRow, error)
	GetPostRelation(ctx context.Context, id int32) (*GetPostRelationRow, error)
	GetPosts(ctx context.Context) ([]*Post, error)
	GetUser(ctx context.Context, id int32) (*GetUserRow, error)
	GetUsers(ctx context.Context) ([]*GetUsersRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (*Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (*Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
